[connections.postgresql]
dialect = "postgresql"
host = "ep-long-credit-a80dfkpn-pooler.eastus2.azure.neon.tech"
port = "5432"
database = "neondb"
username = "neondb_owner"   
password = "npg_qWRk0Df8jHcY"
